### ISSUE TITLE
Questions about evaluation on 3DPW

### ISSUE THREAD

**Issue by zhihaolee** [pixelite1201/agora_evaluation#1]
Thank you for your great work! I have a few questions about evaluation on 3DPW.

1. In table 4 of your paper, why does SPIN-ft-EFT perform worse (PA-MPJPE: 59.3 -> 59.7) after fine-tuned on EFT dataset? In EFT paper, they got PA-MPJPE 58.1 by training SPIN on COCO-All-EFT.

2. In table 2, on the AGORA testset, it seems fine-tuning on AGORA is better than EFT, but in table 5 of your supplementary material, on the 3DPW testset, EFT is better. It seems methods performing better on AGORA may not perform better on the real scenes. Am I right?

Thank you!

**Comment by pixelite1201** [comment]
Thanks for the question!

About 1,  the number EFT reports in paper, 58.1, is for pretrained HMR (trained from scratch on H3.6M) and finetuned on EFT. The number we report is pretrained SPIN (pretrained HMR + finetuned with H3.6M + MPI + COCO + MPII + LSP), then finetuned with EFT.  Also, we follow a slightly different finetuning strategy  because of the perspective camera in AGORA ground truth. This makes the numbers not comparable.

About query 2,  Please note that in Table 5 , all models are trained from scratch. It is true that method trains just on synthetic data can overfit to it and might not perform well on real images. AGORA is a complementary dataset providing features missing in current datasets and helps improve the performance of methods when trained along with real image dataset. As shown in Table 4 when we use AGORA training set to finetune SPIN (already trained on other real image datasets), we get improved performance not only on AGORA testset as shown in Table 2 but also on 3DPW testset as shown in Table 4.

**Comment by zhihaolee** [comment]
Thanks for your reply!

1. Could you tell us the different finetuning strategy, so we can reproduce the results.
2. When you say training from scratch in Table 5, did you use the model pretrained on ImageNet?
3. By the way, how do you know 58.1 of EFT haved trained from scratch on H3.6M, I think they just use the model pretrained on ImageNet.

**Comment by sha2nkt** [comment]
1. We initialize the SPIN model with pretrained weights provided by SPIN and finetune the model on AGORA and EFT respectively using 2D and 3D losses without SMPLify in the loop. Note that due to the mismatch between the perspective camera in AGORA and the weak-perspective camera in SPIN, we didn't use 3D global orientation supervision in training.
2. In Table 5., we start with SPIN model pretrained on H3.6M using only direct supervision. Essentially, we take the randomly initialized SPIN model, and train it using 2D and 3D losses on H3.6M. Note we do not use the HMR discriminator in this step.    
3. You're right. the 58.1 number is obtained using from scratch training on only COCO-EFT data. It is unclear which initialization they use in the paper - it could be Imagenet, H3.6M or random. Nonetheless, it is not comparable to our evaluation scheme as described in 1.

**Comment by zhihaolee** [comment]
Thanks for your clarification @sha2nkt @pixelite1201
