### ISSUE TITLE
Evaluation on test set

### ISSUE THREAD

**Issue by mgholamikn** [pixelite1201/agora_evaluation#21]
Hello, 

Thanks a lot for your great work. I would like to test my framework on the test-set. However, I could not find the camera information for the test set to project the estimated 3D to 2D to prepare the submission files. 

Do we essentially need to project predictions ? can we just use estimated 2d keypoints from openpose. ( In the submission file the shape of 2D keypoint is 24,2 which probably means that we must project predictions to get 2D joints?)

**Comment by pixelite1201** [comment]
Sorry for the delay in reply. In AGORA paper, we have described our evaluation protocol. Since you will be providing multiple prediction per image, the only way to know which person the prediction belongs to is by calculating the distance between predicted 2d keypoints and gt 2d keypoints.  
Openpose keypoints have a different topology so it will not work, so yes you need to provide projected keypoints or atleast the keypoints in the same topology as SMPL.  As also mentioned in the paper, testset is not provided with any labels only the images so there is no ground truth camera information available. Usually most of the methods like HMR, SPIN, PARE etc. assume weak perspective camera and project the 3D to 2D. Maybe you can check out their code.
