### ISSUE TITLE
get occluded person mask

### ISSUE THREAD

**Issue by dldaisy** [pixelite1201/agora_evaluation#7]
Hi,
   I was trying to get the the single person occluded mask in an image. I hope I can get this done by calculating the intersection part of full mask and individual mask. However, I noticed that although the colors of the same person in full mask and individual mask look the same from eyes, the rgb values of the two masks are slightly different when reading out by opencv. Because of this discrepancy, I can not get the single person occluded mask conveniently but have to do something like finding closest color.
  May I ask why don't you use the same color to mark a person in both full mask and individual mask? Thanks a lot!

**Comment by tpsmpi** [comment]
Yes, the RGB values of the occlusion masks (*_00000.png) have small offsets in the body color values compared to the reference colors in the individual body masks. Example: `(55,179,57)` instead of `(55,181,57)` for the first body color.
As you already mentioned it's necessary to compensate for this in your mask processing code when you really need to work with both mask types on a full color level. Tip: try to convert to binary masks as early as possible if you only need a binary result mask at the end.
The list of reference colors can be found [here](https://github.com/microsoft/AirSim/blob/a7e467ebca707bba5b446836331075e90e3e3ab8/docs/seg_rgbs.txt).

AGORA dataset was generated with Unreal Engine 4.24 which did not include built-in functionality for rendering out object segmentation masks. We therefore utilize two separate custom Post Process Materials so that we can render out these masks for any used Unreal environment without further manual environment modifications. 
The Post Process Material for the individual mask directly uses the mask color and produces correctly the reference color. 
The Post Process Material for the occlusion masks uses the results from the previous rendering stage (Z-buffer occlusion) which shifted the reference color slightly.

This is a good example of something which is trivial to do if you use your own OpenGL based renderer, but in contrast game engines perform a lot of color modifications (post process effects, tonemapping) and it takes extra TLC to disable all of these properly.
